name: appdriver
description: DeltaX Driver

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  timeago: ^3.1.0
  path: ^1.8.0
  package_info_plus: ^1.3.0
  double_back_to_close_app: ^2.1.0
  mime: ^1.0.1
  equatable: ^2.0.3
  flutter_bloc: '7.3.1'
  hydrated_bloc: '7.1.0'
  webview_flutter: ^3.0.0
  mobile_number: ^1.0.4
  google_maps_flutter: ^2.1.1
  geocoding: ^2.0.1
  flutter_polyline_points: ^1.0.0
  camera: 0.9.4+3
  after_layout: ^1.1.0
  hive: ^2.0.5
  path_provider: ^2.0.8
  flutter_rating_bar: ^4.0.0
  cron: ^0.4.0
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.0
  flutter_local_notifications: ^9.2.0
  firebase_messaging: ^11.2.4
  firebase_dynamic_links: ^4.0.3
  firebase_analytics: ^9.0.4
  firebase_crashlytics: ^2.4.4
  firebase_core: ^1.10.6
  dio: ^4.0.4
  sms_autofill: ^2.2.0
  shared_preferences: ^2.0.11
  connectivity: ^3.0.6
  flutter_image_compress: ^1.1.0
  image_picker: ^0.8.4+4
  random_string: ^2.3.1
  url_launcher: ^6.0.17
  amplify_flutter: ^0.2.10
  amplify_auth_cognito: ^0.2.10
  amplify_storage_s3: ^0.2.10
  smooth_page_indicator: ^1.0.0+2
  sizer: ^2.0.15
  flutter_background_geolocation: ^4.3.2
  intl: ^0.17.0-nullsafety.2
  file_picker: ^4.3.0
  multi_select_flutter: ^4.0.0
  percent_indicator: ^3.4.0
  pull_to_refresh: ^2.0.0
  background_fetch: ^1.0.3
  pin_code_fields: ^7.3.0
  flutter_dotenv: ^5.0.2
  collection: ^1.15.0
  pusher_client: ^2.0.0
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  hive_generator: ^1.1.1
  flutter_test:
    sdk: flutter

flutter_intl:
  enabled: true
  class_name: S
  main_locale: es_ES
flutter:
  uses-material-design: true
  assets:
    - assets/

